#!/usr/bin/env python3
"""Process raw prototype data into map-ready GeoJSON layers.

Inputs (data/raw/, see ../static-prototype-sources.md):
  - or_tracts_2023/          Census tract boundaries (shapefile)
  - or_acs_population_2023.json  ACS tract population
  - tri_2023_oregon.csv      EPA TRI toxic releases
  - echo_or_major_dischargers.csv  EPA ECHO wastewater facilities
  - egrid2023_data.xlsx      EPA eGRID power plants (national)
  - or_deq_rec_tables_2022.xlsx  Oregon DEQ waste by wasteshed

Outputs (data/processed/):
  - tracts_population.geojson    polygons w/ GEOID + population
  - tri_facilities.geojson       points w/ total releases (lbs)
  - wastewater_facilities.geojson points w/ design flow (MGD)
  - power_plants.geojson         points w/ fuel, capacity, generation, CO2
  - wasteshed_waste.json         tonnage disposed/recovered/generated by wasteshed
"""
import csv
import json
from pathlib import Path

import openpyxl
import shapefile  # pyshp

RAW = Path(__file__).resolve().parent.parent / "raw"
OUT = Path(__file__).resolve().parent.parent / "processed"
OUT.mkdir(exist_ok=True)


def fc(features):
    return {"type": "FeatureCollection", "features": features}


def write(name, obj):
    path = OUT / name
    with open(path, "w") as f:
        json.dump(obj, f)
    n = len(obj["features"]) if "features" in obj else len(obj)
    print(f"{name}: {n} records, {path.stat().st_size // 1024} KB")


def tracts_with_population():
    with open(RAW / "or_acs_population_2023.json") as f:
        rows = json.load(f)
    hdr = rows[0]
    i_pop, i_state, i_county, i_tract = (
        hdr.index("B01003_001E"), hdr.index("state"),
        hdr.index("county"), hdr.index("tract"),
    )
    pop = {r[i_state] + r[i_county] + r[i_tract]: int(r[i_pop]) for r in rows[1:]}

    sf = shapefile.Reader(str(RAW / "or_tracts_2023" / "cb_2023_41_tract_500k"))
    geoid_idx = [f[0] for f in sf.fields[1:]].index("GEOID")
    feats = []
    for sr in sf.iterShapeRecords():
        geoid = sr.record[geoid_idx]
        feats.append({
            "type": "Feature",
            "geometry": sr.shape.__geo_interface__,
            "properties": {"geoid": geoid, "population": pop.get(geoid)},
        })
    missing = sum(1 for f in feats if f["properties"]["population"] is None)
    if missing:
        print(f"  warning: {missing} tracts missing population")
    write("tracts_population.geojson", fc(feats))


def tri_facilities():
    """Aggregate per-chemical rows to one point per facility."""
    by_fac = {}
    with open(RAW / "tri_2023_oregon.csv") as f:
        for row in csv.DictReader(f):
            key = row["2. TRIFD"]
            rec = by_fac.setdefault(key, {
                "name": row["4. FACILITY NAME"].title(),
                "city": row["6. CITY"].title(),
                "county": row["7. COUNTY"].title(),
                "lat": float(row["12. LATITUDE"]),
                "lon": float(row["13. LONGITUDE"]),
                "industry": row["23. INDUSTRY SECTOR"].title(),
                "total_releases_lbs": 0.0,
                "chemicals": 0,
            })
            rec["total_releases_lbs"] += float(row["107. TOTAL RELEASES"] or 0)
            rec["chemicals"] += 1
    feats = [{
        "type": "Feature",
        "geometry": {"type": "Point", "coordinates": [r["lon"], r["lat"]]},
        "properties": {k: (round(v, 1) if isinstance(v, float) else v)
                       for k, v in r.items() if k not in ("lat", "lon")},
    } for r in by_fac.values()]
    write("tri_facilities.geojson", fc(feats))


def wastewater_facilities():
    feats = []
    with open(RAW / "echo_or_major_dischargers.csv") as f:
        for row in csv.DictReader(f):
            if not row.get("FacLat") or not row.get("FacLong"):
                continue
            feats.append({
                "type": "Feature",
                "geometry": {"type": "Point",
                             "coordinates": [float(row["FacLong"]), float(row["FacLat"])]},
                "properties": {
                    "name": row["CWPName"].title(),
                    "permit": row["SourceID"],
                    "city": row["CWPCity"].title(),
                    "design_flow_mgd": float(row["CWPTotalDesignFlowNmbr"])
                        if row.get("CWPTotalDesignFlowNmbr") else None,
                },
            })
    write("wastewater_facilities.geojson", fc(feats))


def power_plants():
    wb = openpyxl.load_workbook(RAW / "egrid2023_data.xlsx", read_only=True)
    ws = wb["PLNT23"]
    it = ws.iter_rows(min_row=2, values_only=True)
    names = next(it)
    col = {n: i for i, n in enumerate(names)}
    feats = []
    for row in it:
        if row[col["PSTATABB"]] != "OR":
            continue
        lat, lon = row[col["LAT"]], row[col["LON"]]
        if lat is None or lon is None:
            continue
        feats.append({
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [float(lon), float(lat)]},
            "properties": {
                "name": row[col["PNAME"]],
                "fuel_category": row[col["PLFUELCT"]],
                "capacity_mw": row[col["NAMEPCAP"]],
                "net_generation_mwh": row[col["PLNGENAN"]],
                "co2_tons": row[col["PLCO2AN"]],
                "nox_tons": row[col["PLNOXAN"]],
                "so2_tons": row[col["PLSO2AN"]],
            },
        })
    write("power_plants.geojson", fc(feats))


def wasteshed_waste():
    wb = openpyxl.load_workbook(RAW / "or_deq_rec_tables_2022.xlsx",
                                read_only=True, data_only=True)
    ws = wb["Table 1"]
    out = {}
    for row in ws.iter_rows(min_row=6, values_only=True):
        name, disposed, recovered, generated, rate = row[0], row[1], row[2], row[3], row[4]
        if not name or not isinstance(disposed, (int, float)):
            continue
        name = str(name).strip().rstrip("0123456789")  # drop footnote markers
        out[name.strip()] = {
            "tons_disposed": round(disposed, 1),
            "tons_recovered": round(recovered, 1),
            "tons_generated": round(generated, 1),
            "recovery_rate": round(rate, 4) if isinstance(rate, (int, float)) else None,
        }
    # population per wasteshed from Table 2 (for per-capita calcs)
    ws2 = wb["Table 2"]
    for row in ws2.iter_rows(min_row=6, values_only=True):
        name = str(row[0]).strip() if row[0] else None
        if name in out and isinstance(row[3], (int, float)):
            out[name]["population"] = round(row[3])
    path = OUT / "wasteshed_waste.json"
    with open(path, "w") as f:
        json.dump(out, f, indent=1)
    print(f"wasteshed_waste.json: {len(out)} wastesheds, {path.stat().st_size // 1024} KB")


if __name__ == "__main__":
    tracts_with_population()
    tri_facilities()
    wastewater_facilities()
    power_plants()
    wasteshed_waste()
